WHITESPACE = _{ " " | "\t" }

ident   = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
number  = @{ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
neg     =  { "-" ~ primary }
primary = _{ number | ident | "(" ~ expr ~ ")" | neg }

add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }

expr    =  { primary ~ ((add | sub | mul | div) ~ primary)* }
assign  =  { ident ~ "=" ~ expr }
program = _{ SOI ~ (assign ~ ";")* ~ expr ~ EOI }
